# UCAD example API test http request

### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJ1c2VybmFtZSI6Im1hdHRpIiwiZW1haWwiOiJtYXR0aUBleGFtcGxlLmNvbSIsInVzZXJfbGV2ZWxfaWQiOjEsImNyZWF0ZWRfYXQiOiIyMDI1LTExLTE3VDEyOjE1OjA3LjAwMFoiLCJpYXQiOjE3NjMzODQ0NjEsImV4cCI6MTc2MzQ3MDg2MX0.Vt3N-fryyzAvUo3cOlbXAWNvfoim9d6-GHQe767a03g

### Note: Install VSCode REST Client extension to use this file

### GET server root
GET http://localhost:3000/


## /media resource

### GET /media
GET http://localhost:3000/api/media

### GET media item by id
GET http://localhost:3000/api/media/6

### GET media items by user (logged in)
GET http://localhost:3000/api/media/user
Authorization: Bearer {{token}}

### Add new media item
POST http://localhost:3000/api/media
content-type: application/json

{
  "filename": "jokukuva.jpg",
  "title": "New image",
  "description": "The description of the new image",
  "user_id": 305,
  "media_type": "image/jpeg"
}

### Add new media item including media file
POST http://localhost:3000/api/media
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="title"

New cat image
------Boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./test-cat.png
------Boundary--

### Update existing media item
PUT http://localhost:3000/api/media/27
content-type: application/json

{
  "title": "Basement modified",
  "description": "Some new description",
}

### Delete existing media item
DELETE http://localhost:3000/api/media/2
Authorization: Bearer {{token}}

######################

## /users resource

### GET /users
GET http://localhost:3000/api/users

### GET user by id
GET http://localhost:3000/api/users/27

### Add new user
POST http://localhost:3000/api/users
content-type: application/json

{
  "username": "matti",
  "password": "salakala",
  "email": "matti@example.com" 
}

### Login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "username": "matti",
  "password": "salakala"
}

### Auth GET me
GET http://localhost:3000/api/auth/me
Authorization: Bearer {{token}}


### Update existing user
PUT http://localhost:3000/api/users/27
content-type: application/json

{
  "TODO": "FIX THIS REQUEST" 
}

### Delete existing user
DELETE http://localhost:3000/api/users/27


##############################3

## /items dummy resource mock data
### GET /items
GET http://localhost:3000/api/items

### GET item by id
GET http://localhost:3000/api/items/27

### Add new item
POST http://localhost:3000/api/items
content-type: application/json

{
  "name": "New Item"
}

### Update existing item
PUT http://localhost:3000/api/items/27
content-type: application/json

{
  "name": "New name for the item"
}

### Delete existing item
DELETE http://localhost:3000/api/items/27
