# UCAD example API test http request

### GET server root
GET http://localhost:3000/

## /items mock data

### GET /items
GET http://localhost:3000/items

### GET item by id
GET http://localhost:3000/items/27

### Add new item
POST http://localhost:3000/items
content-type: application/json

{
  "name": "New Item"
}

### Update existing item
PUT http://localhost:3000/items/27
content-type: application/json

{
  "name": "New name for the item"
}

### Delete existing item
DELETE http://localhost:3000/items/27
